/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NOKORMC Top Up Store API
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * Verify if a game player ID is valid
 * @summary Verify player ID
 */
export const VerifyPlayerIdBody = zod.object({
  game: zod.enum(["mlbb", "freefire"]),
  playerId: zod.string(),
  serverId: zod.string().optional(),
});

export const VerifyPlayerIdResponse = zod.object({
  valid: zod.boolean(),
  playerName: zod.string().optional(),
  playerId: zod.string(),
  serverId: zod.string().optional(),
});

/**
 * Get list of available top-up products for a game
 * @summary Get top-up products
 */
export const GetProductsQueryParams = zod.object({
  game: zod.enum(["mlbb", "freefire"]),
});

export const GetProductsResponse = zod.object({
  game: zod.string(),
  products: zod.array(
    zod.object({
      id: zod.string(),
      name: zod.string(),
      amount: zod.number(),
      price: zod.number(),
      currency: zod.string(),
      bonus: zod.string().optional(),
      image: zod.string().optional(),
    }),
  ),
});

/**
 * Create a payment order with ABA QR
 * @summary Create payment
 */
export const CreatePaymentBody = zod.object({
  amount: zod.number(),
  currency: zod.string(),
  orderId: zod.string(),
  description: zod.string(),
  firstName: zod.string().optional(),
  lastName: zod.string().optional(),
  email: zod.string().optional(),
  phone: zod.string().optional(),
});

export const CreatePaymentResponse = zod.object({
  transactionId: zod.string(),
  qrCode: zod.string(),
  deeplink: zod.string().optional(),
  amount: zod.number(),
  currency: zod.string(),
  status: zod.string(),
});

/**
 * Check the status of a payment transaction
 * @summary Check payment status
 */
export const CheckPaymentStatusParams = zod.object({
  transactionId: zod.coerce.string(),
});

export const CheckPaymentStatusResponse = zod.object({
  transactionId: zod.string(),
  status: zod.enum(["pending", "success", "failed", "expired"]),
  amount: zod.number(),
  currency: zod.string(),
  paidAt: zod.string().optional(),
});

/**
 * Create a new top-up order
 * @summary Create top-up order
 */
export const CreateOrderBody = zod.object({
  game: zod.enum(["mlbb", "freefire"]),
  playerId: zod.string(),
  serverId: zod.string().optional(),
  playerName: zod.string().optional(),
  productId: zod.string(),
  amount: zod.number(),
  price: zod.number(),
  transactionId: zod.string().optional(),
});

/**
 * Get list of orders
 * @summary Get orders
 */
export const GetOrdersResponseItem = zod.object({
  id: zod.number(),
  game: zod.string(),
  playerId: zod.string(),
  serverId: zod.string().optional(),
  playerName: zod.string().optional(),
  productId: zod.string(),
  productName: zod.string().optional(),
  amount: zod.number(),
  price: zod.number(),
  status: zod.enum(["pending", "processing", "completed", "failed"]),
  transactionId: zod.string().optional(),
  createdAt: zod.string(),
});
export const GetOrdersResponse = zod.array(GetOrdersResponseItem);
