/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NOKORMC Top Up Store API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type VerifyPlayerIdRequestGame =
  (typeof VerifyPlayerIdRequestGame)[keyof typeof VerifyPlayerIdRequestGame];

export const VerifyPlayerIdRequestGame = {
  mlbb: "mlbb",
  freefire: "freefire",
} as const;

export interface VerifyPlayerIdRequest {
  game: VerifyPlayerIdRequestGame;
  playerId: string;
  serverId?: string;
}

export interface VerifyPlayerIdResponse {
  valid: boolean;
  playerName?: string;
  playerId: string;
  serverId?: string;
}

export interface Product {
  id: string;
  name: string;
  amount: number;
  price: number;
  currency: string;
  bonus?: string;
  image?: string;
}

export interface ProductListResponse {
  game: string;
  products: Product[];
}

export interface CreatePaymentRequest {
  amount: number;
  currency: string;
  orderId: string;
  description: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
}

export interface CreatePaymentResponse {
  transactionId: string;
  qrCode: string;
  deeplink?: string;
  amount: number;
  currency: string;
  status: string;
}

export type PaymentStatusResponseStatus =
  (typeof PaymentStatusResponseStatus)[keyof typeof PaymentStatusResponseStatus];

export const PaymentStatusResponseStatus = {
  pending: "pending",
  success: "success",
  failed: "failed",
  expired: "expired",
} as const;

export interface PaymentStatusResponse {
  transactionId: string;
  status: PaymentStatusResponseStatus;
  amount: number;
  currency: string;
  paidAt?: string;
}

export type CreateOrderRequestGame =
  (typeof CreateOrderRequestGame)[keyof typeof CreateOrderRequestGame];

export const CreateOrderRequestGame = {
  mlbb: "mlbb",
  freefire: "freefire",
} as const;

export interface CreateOrderRequest {
  game: CreateOrderRequestGame;
  playerId: string;
  serverId?: string;
  playerName?: string;
  productId: string;
  amount: number;
  price: number;
  transactionId?: string;
}

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const OrderStatus = {
  pending: "pending",
  processing: "processing",
  completed: "completed",
  failed: "failed",
} as const;

export interface Order {
  id: number;
  game: string;
  playerId: string;
  serverId?: string;
  playerName?: string;
  productId: string;
  productName?: string;
  amount: number;
  price: number;
  status: OrderStatus;
  transactionId?: string;
  createdAt: string;
}

export interface ErrorResponse {
  error: string;
  message: string;
}

export type GetProductsParams = {
  game: GetProductsGame;
};

export type GetProductsGame =
  (typeof GetProductsGame)[keyof typeof GetProductsGame];

export const GetProductsGame = {
  mlbb: "mlbb",
  freefire: "freefire",
} as const;
