/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NOKORMC Top Up Store API
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateOrderRequest,
  CreatePaymentRequest,
  CreatePaymentResponse,
  ErrorResponse,
  GetProductsParams,
  HealthStatus,
  Order,
  PaymentStatusResponse,
  ProductListResponse,
  VerifyPlayerIdRequest,
  VerifyPlayerIdResponse,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns server health status
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Verify if a game player ID is valid
 * @summary Verify player ID
 */
export const getVerifyPlayerIdUrl = () => {
  return `/api/topup/verify-id`;
};

export const verifyPlayerId = async (
  verifyPlayerIdRequest: VerifyPlayerIdRequest,
  options?: RequestInit,
): Promise<VerifyPlayerIdResponse> => {
  return customFetch<VerifyPlayerIdResponse>(getVerifyPlayerIdUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(verifyPlayerIdRequest),
  });
};

export const getVerifyPlayerIdMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof verifyPlayerId>>,
    TError,
    { data: BodyType<VerifyPlayerIdRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof verifyPlayerId>>,
  TError,
  { data: BodyType<VerifyPlayerIdRequest> },
  TContext
> => {
  const mutationKey = ["verifyPlayerId"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof verifyPlayerId>>,
    { data: BodyType<VerifyPlayerIdRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return verifyPlayerId(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type VerifyPlayerIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof verifyPlayerId>>
>;
export type VerifyPlayerIdMutationBody = BodyType<VerifyPlayerIdRequest>;
export type VerifyPlayerIdMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Verify player ID
 */
export const useVerifyPlayerId = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof verifyPlayerId>>,
    TError,
    { data: BodyType<VerifyPlayerIdRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof verifyPlayerId>>,
  TError,
  { data: BodyType<VerifyPlayerIdRequest> },
  TContext
> => {
  return useMutation(getVerifyPlayerIdMutationOptions(options));
};

/**
 * Get list of available top-up products for a game
 * @summary Get top-up products
 */
export const getGetProductsUrl = (params: GetProductsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/api/topup/products?${stringifiedParams}`
    : `/api/topup/products`;
};

export const getProducts = async (
  params: GetProductsParams,
  options?: RequestInit,
): Promise<ProductListResponse> => {
  return customFetch<ProductListResponse>(getGetProductsUrl(params), {
    ...options,
    method: "GET",
  });
};

export const getGetProductsQueryKey = (params?: GetProductsParams) => {
  return [`/api/topup/products`, ...(params ? [params] : [])] as const;
};

export const getGetProductsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProducts>>,
  TError = ErrorType<unknown>,
>(
  params: GetProductsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProducts>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProductsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProducts>>> = ({
    signal,
  }) => getProducts(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getProducts>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetProductsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProducts>>
>;
export type GetProductsQueryError = ErrorType<unknown>;

/**
 * @summary Get top-up products
 */

export function useGetProducts<
  TData = Awaited<ReturnType<typeof getProducts>>,
  TError = ErrorType<unknown>,
>(
  params: GetProductsParams,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getProducts>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetProductsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a payment order with ABA QR
 * @summary Create payment
 */
export const getCreatePaymentUrl = () => {
  return `/api/payment/create`;
};

export const createPayment = async (
  createPaymentRequest: CreatePaymentRequest,
  options?: RequestInit,
): Promise<CreatePaymentResponse> => {
  return customFetch<CreatePaymentResponse>(getCreatePaymentUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPaymentRequest),
  });
};

export const getCreatePaymentMutationOptions = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPayment>>,
    TError,
    { data: BodyType<CreatePaymentRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createPayment>>,
  TError,
  { data: BodyType<CreatePaymentRequest> },
  TContext
> => {
  const mutationKey = ["createPayment"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createPayment>>,
    { data: BodyType<CreatePaymentRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createPayment(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreatePaymentMutationResult = NonNullable<
  Awaited<ReturnType<typeof createPayment>>
>;
export type CreatePaymentMutationBody = BodyType<CreatePaymentRequest>;
export type CreatePaymentMutationError = ErrorType<ErrorResponse>;

/**
 * @summary Create payment
 */
export const useCreatePayment = <
  TError = ErrorType<ErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createPayment>>,
    TError,
    { data: BodyType<CreatePaymentRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createPayment>>,
  TError,
  { data: BodyType<CreatePaymentRequest> },
  TContext
> => {
  return useMutation(getCreatePaymentMutationOptions(options));
};

/**
 * Check the status of a payment transaction
 * @summary Check payment status
 */
export const getCheckPaymentStatusUrl = (transactionId: string) => {
  return `/api/payment/check/${transactionId}`;
};

export const checkPaymentStatus = async (
  transactionId: string,
  options?: RequestInit,
): Promise<PaymentStatusResponse> => {
  return customFetch<PaymentStatusResponse>(
    getCheckPaymentStatusUrl(transactionId),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getCheckPaymentStatusQueryKey = (transactionId: string) => {
  return [`/api/payment/check/${transactionId}`] as const;
};

export const getCheckPaymentStatusQueryOptions = <
  TData = Awaited<ReturnType<typeof checkPaymentStatus>>,
  TError = ErrorType<unknown>,
>(
  transactionId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof checkPaymentStatus>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCheckPaymentStatusQueryKey(transactionId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof checkPaymentStatus>>
  > = ({ signal }) =>
    checkPaymentStatus(transactionId, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!transactionId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof checkPaymentStatus>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CheckPaymentStatusQueryResult = NonNullable<
  Awaited<ReturnType<typeof checkPaymentStatus>>
>;
export type CheckPaymentStatusQueryError = ErrorType<unknown>;

/**
 * @summary Check payment status
 */

export function useCheckPaymentStatus<
  TData = Awaited<ReturnType<typeof checkPaymentStatus>>,
  TError = ErrorType<unknown>,
>(
  transactionId: string,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof checkPaymentStatus>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getCheckPaymentStatusQueryOptions(
    transactionId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * Create a new top-up order
 * @summary Create top-up order
 */
export const getCreateOrderUrl = () => {
  return `/api/orders`;
};

export const createOrder = async (
  createOrderRequest: CreateOrderRequest,
  options?: RequestInit,
): Promise<Order> => {
  return customFetch<Order>(getCreateOrderUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createOrderRequest),
  });
};

export const getCreateOrderMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOrder>>,
    TError,
    { data: BodyType<CreateOrderRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOrder>>,
  TError,
  { data: BodyType<CreateOrderRequest> },
  TContext
> => {
  const mutationKey = ["createOrder"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOrder>>,
    { data: BodyType<CreateOrderRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return createOrder(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOrderMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOrder>>
>;
export type CreateOrderMutationBody = BodyType<CreateOrderRequest>;
export type CreateOrderMutationError = ErrorType<unknown>;

/**
 * @summary Create top-up order
 */
export const useCreateOrder = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOrder>>,
    TError,
    { data: BodyType<CreateOrderRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createOrder>>,
  TError,
  { data: BodyType<CreateOrderRequest> },
  TContext
> => {
  return useMutation(getCreateOrderMutationOptions(options));
};

/**
 * Get list of orders
 * @summary Get orders
 */
export const getGetOrdersUrl = () => {
  return `/api/orders`;
};

export const getOrders = async (options?: RequestInit): Promise<Order[]> => {
  return customFetch<Order[]>(getGetOrdersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetOrdersQueryKey = () => {
  return [`/api/orders`] as const;
};

export const getGetOrdersQueryOptions = <
  TData = Awaited<ReturnType<typeof getOrders>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetOrdersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrders>>> = ({
    signal,
  }) => getOrders({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getOrders>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOrdersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOrders>>
>;
export type GetOrdersQueryError = ErrorType<unknown>;

/**
 * @summary Get orders
 */

export function useGetOrders<
  TData = Awaited<ReturnType<typeof getOrders>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<Awaited<ReturnType<typeof getOrders>>, TError, TData>;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetOrdersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}
