/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NOKORMC Top Up Store API
 * OpenAPI spec version: 0.1.0
 */

export interface CreatePaymentRequest {
  amount: number;
  currency: string;
  orderId: string;
  description: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phone?: string;
}
