/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NOKORMC Top Up Store API
 * OpenAPI spec version: 0.1.0
 */

export type GetProductsGame =
  (typeof GetProductsGame)[keyof typeof GetProductsGame];

export const GetProductsGame = {
  mlbb: "mlbb",
  freefire: "freefire",
} as const;
