/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NOKORMC Top Up Store API
 * OpenAPI spec version: 0.1.0
 */
import type { OrderStatus } from "./orderStatus";

export interface Order {
  id: number;
  game: string;
  playerId: string;
  serverId?: string;
  playerName?: string;
  productId: string;
  productName?: string;
  amount: number;
  price: number;
  status: OrderStatus;
  transactionId?: string;
  createdAt: string;
}
