/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NOKORMC Top Up Store API
 * OpenAPI spec version: 0.1.0
 */

export type PaymentStatusResponseStatus =
  (typeof PaymentStatusResponseStatus)[keyof typeof PaymentStatusResponseStatus];

export const PaymentStatusResponseStatus = {
  pending: "pending",
  success: "success",
  failed: "failed",
  expired: "expired",
} as const;
