/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NOKORMC Top Up Store API
 * OpenAPI spec version: 0.1.0
 */
import type { Product } from "./product";

export interface ProductListResponse {
  game: string;
  products: Product[];
}
